import os
MY_ENV = 'dev'

# MONGO DATABASE SETTINGS
MONGO_DB_NAME = 'mlp'
MONGO_DB_PORT = 27017
MONGO_DB_HOSTNAME = 'localhost'


DEBUG = True
PORT = 4003
HOST = "127.0.0.1"
MONGODB_URI = "mongodb://{MONGODB_HOST}:{MONGODB_PORT}/{MONGODB_DB}".format(
    MONGODB_HOST=MONGO_DB_HOSTNAME, MONGODB_PORT=MONGO_DB_PORT, MONGODB_DB=MONGO_DB_NAME)

# Enabled modules
ENABLE_MODULES = ['kmeans', 'ImageNet']

